In [1]:
# numpyのインポート
import numpy as np
from pprint import pprint

## 1. NumPy配列の形状変換  
ndarrayの形状変換にはメソッドndarray.reshape()が用いられ，要素を変えることなく形状のみを変えることができます．  
### メソッドndarray.reshape()  
メソッドndarray.reshape(newshape, order='C')の引数は，newshape : 変換後の配列の形状(intもしくはタプルかリスト), 変換順序(初期値'C', 'F', 'A')となります．3つ目の引数は省略されることが多いです．  
【例題】メソッドndarray.reshape()を用いた形状変換をします．以下のコードを読んで実行してみましょう．

In [2]:
# 1x24のベクトルを生成
numpy_l = np.arange(24)
print('ndarray : ', numpy_l)
print('形状    : ', numpy_l.shape)
print('次元数  : ', numpy_l.ndim)

ndarray :  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
形状    :  (24,)
次元数  :  1


In [9]:
# 4x6に変換
numpy_4_6 = numpy_l.reshape(4, -1)
pprint(numpy_4_6)
print('変換後の形状 : ', numpy_4_6.shape)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])
変換後の形状 :  (4, 6)


- まずは3x4に形状変換しました．変換後のndarrayの形状が3x4になっていれば成功です．要素は変わらず形状だけ変化していることを確認してください．  
- 引数に与える変換後の配列の形状は例題1のように各次元の値を順に指定してもいいし，以下のようにタプルやリストを指定してもOKです．

In [10]:
# 2x3x4に変換
numpy_2_3_4 = numpy_l.reshape([2, 3, -1])
pprint(numpy_2_3_4)
print('変換後の形状 : ', numpy_2_3_4.shape)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])
変換後の形状 :  (2, 3, 4)


- 変換後の形状が2x3x4になっていれば成功です．このようにndarray.reshape()に変換後の形状を与えることで形状の変換が可能です．  
- 変換後の形状と変換前の形状が異なる場合はエラーを返します．  

変換順序を指定すると以下のようになります．

In [13]:
print('変換前 : ', numpy_l)

# order='C'を指定
print('C')
pprint(numpy_l.reshape(4, -1, order='C'))

# order = 'F'を指定
print('F')
pprint(numpy_l.reshape(4, -1, order='F'))

# order = 'F'を指定
print('F')
pprint(numpy_l.reshape(6, -1, order='F'))

変換前 :  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
C
array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])
F
array([[ 0,  4,  8, 12, 16, 20],
       [ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23]])
F
array([[ 0,  6, 12, 18],
       [ 1,  7, 13, 19],
       [ 2,  8, 14, 20],
       [ 3,  9, 15, 21],
       [ 4, 10, 16, 22],
       [ 5, 11, 17, 23]])


- 以上のように変換順序が異なります．

【問題】メソッドndarray.reshape()を用いて以下の配列を5x10へ形状変換してみましょう．変換順序は初期状態とします．

In [6]:
# 変換前の配列
numpy_l = np.arange(50)
pprint(numpy_l)

# 5x10へ変換
numpy_5_10 = numpy_l.reshape(5, 10)
print('変換後 : ')
pprint(numpy_5_10)
print('形状 : ', numpy_5_10.shape)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])
変換後 : 
array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])
形状 :  (5, 10)


- 形状が(5, 10)となっていれば正解です．  
- 要素は変化せず，形状のみ変化していることを確認してください．

## 2. 形状の指定に-1を用いることで適切な値に設定する  
メソッドndarray.reshapeでは形状の指定で-1を与えることで要素数に合わせて形状を自動的に適切な値へ設定することができます．サイズの大きな配列の形状を変換する際によく使用するので覚えておきましょう．  
【例題】形状の指定に-1を用いてどのような挙動をするか見てみます．以下のコードを読んで実行してみましょう．

In [7]:
numpy_l = np.arange(24)
print('変換前')
pprint(numpy_l)

# 4と-1を指定してみる
numpy_4_ = numpy_l.reshape(4, -1)
print('変換後(4, -1)')
pprint(numpy_4_)
print('形状', numpy_4_.shape)

print('---------------------')

# 2, -1, 4を指定してみる
numpy_2__4 = numpy_l.reshape(2, -1, 4)
print('変換後(2, -1, 4)')
pprint(numpy_2__4)
print('形状', numpy_2__4.shape)

変換前
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])
変換後(4, -1)
array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])
形状 (4, 6)
---------------------
変換後(2, -1, 4)
array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])
形状 (2, 3, 4)


- -1を指定した部分が自動的に指定されていることを確認しましょう．どちらの場合も適切に値が指定されています．  
- -1を指定できるのは1つの次元に対してのみで，2つ以上の次元に指定するとエラーとなるので注意しましょう．  
- この機能は大きな配列を変換する際に重宝します．

【問題】4x4の配列を2x?x4の配列に変換してみましょう．

In [8]:
# 4x4の配列
numpy_4_4 = np.arange(16).reshape(4, 4)

# 2x?x4の配列に変換
numpy_2__4 = numpy_4_4.reshape(2, -1, 4)
print('変換後')
pprint(numpy_2__4)

変換後
array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])


- 変換後の配列が  
[[[0 1 2 3]  
  [4 5 6 7]]  
[[8 9 10 11]  
  [12 13 14 15]]]  
となっていれば正解です．  
- 形状が自動的に2, 2, 4になっていることを確認しましょう．