In [35]:
# numpyのインポート
import numpy as np

## 1. 2つのNumPy配列の要素ごとの最大値・最小値を取得  
numpy.maximum()を用いることで，複数のndarrayの要素ごとの最大値を求め，新たなndarrayを生成することができます．また，numpy.mimimum()を用いることで，同様に最小値を求めることができます.  
【例題1】2つのndarrayの最大値を求めます．以下のコードを読んで，実行してみましょう．

In [36]:
# 2x3のndarrayを2つ作成
numpy_1 = np.arange(6).reshape(2, 3)
print('ndarrayその1')
print(numpy_1)

numpy_2 = np.array([[2, 5, 1],[1, 0, 3]])
print('ndarrayその2')
print(numpy_2)

ndarrayその1
[[0 1 2]
 [3 4 5]]
ndarrayその2
[[2 5 1]
 [1 0 3]]


In [37]:
# 要素ごとの最大値を求める
print('要素ごとの最大値')
print(np.maximum(numpy_1, numpy_2))

要素ごとの最大値
[[2 5 2]
 [3 4 5]]


- 要素ごとの最大値が  
[[2 5 2]  
  [3 4 5]]  
 となっていれば成功です．  
- 2つの配列の最大値が要素ごとに求められていることを確認しましょう．

【例題2】2つのndarrayの最小値を求めます．以下のコードを読んで，実行してみましょう．

In [38]:
# 2つのndarrayを表示
print('ndarrayその1')
print(numpy_1)
print('ndarrayその2')
print(numpy_2)

ndarrayその1
[[0 1 2]
 [3 4 5]]
ndarrayその2
[[2 5 1]
 [1 0 3]]


In [39]:
# 要素ごとの最小値を求める
print('要素ごとの最小値')
print(np.minimum(numpy_1, numpy_2))

要素ごとの最小値
[[0 1 1]
 [1 0 3]]


- 要素ごとの最小値が  
[[0 1 1]  
 [1 0 3]]  
 となっていれば成功です．  
- 2つの配列の最小値が要素ごとに求められていることを確認しましょう．

【問題】以下に示す2つのndarrayの最大値と最小値をそれぞれ求めてみましょう．

In [40]:
# 2x3のndarrayを2つ作成
numpy_1 = np.array([[5, 6, 2], [2, 3, 9]])
print('ndarrayその1')
print(numpy_1)

numpy_2 = np.array([[0, 5, 7],[1, 5, 3]])
print('ndarrayその2')
print(numpy_2)

ndarrayその1
[[5 6 2]
 [2 3 9]]
ndarrayその2
[[0 5 7]
 [1 5 3]]


In [41]:
# 要素ごとの最大値を求める
maximum_ndarray = np.maximum(numpy_1, numpy_2)
print('要素ごとの最大値')
print(maximum_ndarray)

# 要素ごとの最小値を求める
minimum_ndarray = np.minimum(numpy_1, numpy_2)
print('要素ごとの最小値')
print(minimum_ndarray)

要素ごとの最大値
[[5 6 7]
 [2 5 9]]
要素ごとの最小値
[[0 5 2]
 [1 3 3]]


- 要素ごとの最大値が  
[[2 5 2]  
[3 4 5]]  
要素ごとの最小値が  
[[0 1 1]  
[1 0 3]]  
となっていれば正解です.

最大値と最小値を求める方法として，メソッドmax(), min()がありますが，これらは単独のndarrayの列ごと・行ごとの最大値・最小値を取得するメソッドになりますので混同しないように注意してください．

## 2つのNumPy配列の全ての要素が等しいか比較  
2つのndaarayのすべての要素が等しいか比較するには，numpy.array_equal()を用いて比較することが可能です.  
【例題】2つのndarrayのすべての要素が等しいかどうかを比較します．以下のコードを読んで実行してみましょう．

In [42]:
# 要素が等しい場合
# ndarrayの生成
numpy_1 = np.arange(6).reshape(2, 3)
print('ndarrayその1')
print(numpy_1)

numpy_2 = numpy_1
print('ndarrayその2')
print(numpy_2)

ndarrayその1
[[0 1 2]
 [3 4 5]]
ndarrayその2
[[0 1 2]
 [3 4 5]]


In [43]:
# 全ての要素が等しいか比較
print(np.array_equal(numpy_1, numpy_2))

True


In [44]:
# 要素が等しくない場合
# ndarrayの生成
numpy_1 = np.arange(6).reshape(2, 3)
print('ndarrayその1')
print(numpy_1)

numpy_2 = np.arange(6, 12).reshape(2, 3)
print('ndarrayその2')
print(numpy_2)

ndarrayその1
[[0 1 2]
 [3 4 5]]
ndarrayその2
[[ 6  7  8]
 [ 9 10 11]]


In [45]:
# 全ての要素が等しいか比較
print(np.array_equal(numpy_1, numpy_2))

False


- それぞれ実行結果がTrue, Falseとなれば成功です．  
- np.array_equalの結果はブール値で帰ってくることを確認しましょう.

【問題】以下の2つのndarrayの要素が等しいか比較してみましょう．

In [46]:
# ndarrayの生成
numpy_1 = np.arange(9).reshape(3, 3)
print('ndarrayその1')
print(numpy_1)
numpy_2 = numpy_1
print('ndarrayその2')
print(numpy_2)

ndarrayその1
[[0 1 2]
 [3 4 5]
 [6 7 8]]
ndarrayその2
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [47]:
# 全ての要素が等しいか比較
print(np.array_equal(numpy_1, numpy_2))

True


- 実行結果がTrueとなっていれば正解です．