In [8]:
# numpyのインポート
import numpy as np

## 1. ブールインデックス参照  
配列の各要素に対してブール値を与えることで，Trueの部分の要素を取り出した配列を新たに生成することができます．  
【例題】ブールインデックス参照を用いて要素の取り出しを行います．以下のコードを読んで実行してみましょう．

In [9]:
# 配列の生成
numpy_l = np.arange(5)
print(numpy_l)

# ブールインデックス参照を用いて取り出し
print('実行結果')
print(numpy_l[np.array([True, True, True, False, False]) ])

[0 1 2 3 4]
実行結果
[0 1 2]


- 実行結果が  
[0 1 2]  
となっていれば成功です．  
- このように，ブール値を与えることで要素を取り出すことができることを確認しましょう．  

また，ブール値ではなく条件式を書くことで各要素について比較することができます．

In [10]:
print(numpy_l)

# 比較する
print('実行結果')
print(numpy_l[numpy_l < 3])

[0 1 2 3 4]
実行結果
[0 1 2]


- このように条件式に合う値を取り出すことができます．

【問題】以下の配列について，10で割り切れるものに-1を代入してみましょう．

In [11]:
# 配列の生成
numpy_l = np.array([0, 5, 10, 15, 20, 25, 30])

# 比較
numpy_l[numpy_l % 10 == 0] = -1

print(numpy_l)

[-1  5 -1 15 -1 25 -1]


- 生成された配列が  
[-1 5 -1 15 -1 25 -1]  
となっていれば正解です．

## 2. 整数値のリストを用いた要素の取り出し  
整数値のリスト，ndarrayを用いて配列から要素を取り出した配列を新たに生成することも可能です．  
【例題】リストを使って配列から要素を取り出します．以下のコードを読んで実行してみましょう．

In [18]:
# 配列の生成
numpy_l = np.arange(6)
print(numpy_l)

# 要素の取り出し
print('配列の0, 2, 4, -1番目を指定')
print(numpy_l[[0, 2, 4, -1]])

[0 1 2 3 4 5]
配列の0, 2, 4, -1番目を指定
[0 2 4 5]


- 実行結果が[ 0 2 4 5]となっていれば成功です．  
- 整数のリストを与えることで要素の取り出しができることを確認しましょう．

二次元配列の例も見てみましょう．二次元以上の配列ではスライスを用いて任意の行・列を取り出すことができます．

In [27]:
# 配列の生成
numpy_l = np.arange(9).reshape(3, 3)
print(numpy_l)

# 要素の取り出し
print('0, 2行目を取り出し')
print(numpy_l[[0, 2]])

print('0, 2列目を取り出し')
print(numpy_l[:, [0, 2]])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
0, 2行目を取り出し
[[0 1 2]
 [6 7 8]]
0, 2列目を取り出し
[[0 2]
 [3 5]
 [6 8]]


- それぞれ行と列について要素の取り出しが行われていることを確認しましょう．

【問題】以下の配列から0, 2列目を取り出してみましょう．

In [24]:
# 配列の生成
numpy_l = np.arange(12).reshape(3, 4)
print(numpy_l)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [25]:
print(numpy_l[:, [0, 2]])

[[ 0  2]
 [ 4  6]
 [ 8 10]]


- 実行結果が  
[[0 2]  
[4 6]  
[ 8 10]  
となっていれば正解です．