In [3]:
# numpyのインポート
import numpy as np

## 1. 多次元のNumPy配列  
Numpyの配列ndarrayは多次元配列を扱うことができます．  
【例題】二次元以上の配列を生成します．以下のコードを読んで実行してみましょう．

In [8]:
# 2x2x3配列の生成
numpy_l = np.array([[[0, 1, 2], [3, 4, 5]], [[6, 7, 8], [9, 10, 11]]])
print(numpy_l)
print(numpy_l.shape)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
(2, 2, 3)


- 実行結果が  
[[[0 1 2]  
[3 4 5 ]]  
[[6 7 8]  
[9 10 11]]]  
となっていれば成功です．  
- 三次元配列(2x2x3)が生成されていることを確認しましょう．  

【問題】2x3x3の配列を作ってみましょう．  

In [9]:
print(np.arange(18).reshape(2, 3, 3))

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]


- 2x3x3の配列ができていれば成功です．

## 2. 二次元以上のnumpy.dot()  
二次元以上の配列の積を求める際にもnumpy.dot()を使うことができますが，配列の形状について注意する必要があります．二次元以上の配列の積を求める場合は，一つ目の配列の列数(横方向の要素数)と二つ目の配列の行数(縦方向の要素数)が一致している必要があります．  
【例題】2x3の配列と3x2の配列の積を求めます．以下のコードを読んで実行してみましょう．

In [13]:
# 配列の生成
numpy_1 = np.arange(6).reshape(2, 3)
print('配列1')
print(numpy_1)
numpy_2 = np.arange(6).reshape(3, 2)
print('配列2')
print(numpy_2)

# 行列の積
print('計算結果')
print(np.dot(numpy_1, numpy_2))

配列1
[[0 1 2]
 [3 4 5]]
配列2
[[0 1]
 [2 3]
 [4 5]]
計算結果
[[10 13]
 [28 40]]


- 計算結果が  
[[10 13]  
[28 40]]  
となっていれば成功です．  
- 二次元以上の配列もnumpy.dot()によって積が計算できることを確認しましょう．  