In [36]:
# numpyのインポート
import numpy as np

## 1. NumPy配列の列ごとの合計，平均を算出
numpy.sum(), numpy.mean()を用いることでndarray全体の合計や平均を算出できますが，さらに引数axisを与えることで行ごとや列ごとに結果を得ることができます．  
【例題1】ndarrayの合計を求める際に，axisを与えなかった場合とaxisに0を与えた場合を比較してみましょう.以下のコードを読んで実行してください．

In [37]:
# 3x3の配列を作成
numpy_l = np.arange(9).reshape(3, 3)
print(numpy_l.shape)
print(numpy_l)

(3, 3)
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [38]:
# axisを与えない場合
print('axisを与えない : ', np.sum(numpy_l))
# axis = 0を与えた場合
print('axis = 0       : ', np.sum(numpy_l, axis=0))

axisを与えない :  36
axis = 0       :  [ 9 12 15]


- axisを与えなかった場合に36が，axisを0とした場合に[ 9 12 15 ]が求められていれば成功です．
- axisを与えない場合はndarray全体の合計を算出し，axisに0を与えることで列ごとの合計を算出できることが分かります．

【例題2】ndarrayの平均を求める際に，axisを与えなかった場合とaxisに0を与えた場合を比較してみましょう.以下のコードを読んで実行してください．

In [39]:
# axisを与えない場合
print('axisを与えない : ', np.mean(numpy_l))
# axis = 0を与えた場合
print('axis = 0       : ', np.mean(numpy_l, axis=0))

axisを与えない :  4.0
axis = 0       :  [3. 4. 5.]


- axisを与えなかった場合に4.0が，axisを0とした場合に「3．4．5．]が求められていれば成功です．
- np.mean()もnp.sum()と同様に，axisを与えない場合はndarray全体の合計を算出し，axisに0を与えることで列ごとの合計を算出できることが分かります．

【問題】以下に示す配列の列ごとの合計と列ごとの平均を求めてみましょう．

In [40]:
# 4x3の配列を作成
numpy_l = np.arange(12).reshape(4, 3)
print(numpy_l.shape)
print(numpy_l)

(4, 3)
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [41]:
# 列ごとの合計
print('列ごとの合計 : ', np.sum(numpy_l, axis = 0))
# 列ごとの平均
print('列ごとの平均 : ', np.mean(numpy_l, axis = 0))

列ごとの合計 :  [18 22 26]
列ごとの平均 :  [4.5 5.5 6.5]


- 列ごとの平均が [18 22 26]  
- 列ごとの合計が [4.5 5.5 6.5]

と表示されていれば成功です．

## 2. NumPy配列の行ごとの合計，平均の算出

先ほどは引数を与えない場合と，axis=0を与えた場合にそれぞれ全体の演算と，列ごとの演算ができることを確認しました．ここではaxisに1を与えることによって行ごとの演算を行うことができることを確認しましょう．  
【例題】ndarrayの行ごとの合計と平均をaxisに1を与えることによって求めます．以下のコードを読んで実行してみましょう．

In [42]:
# 3x3の配列を作成
numpy_l = np.arange(9).reshape(3, 3)
print(numpy_l.shape)
print(numpy_l)

(3, 3)
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [43]:
# 行ごとの合計
print(np.sum(numpy_l, axis=1))
# 行ごとの平均
print(np.mean(numpy_l, axis=1))

[ 3 12 21]
[1. 4. 7.]


- 行ごとの合計が[ 2 12 21]に，行ごとの平均が[1. 4. 7.]になっていれば成功です．
- axisに1を与えることで行ごとの演算ができることがわかります．

【問題】以下に示す配列の行ごとの合計と行ごとの平均を求めてみましょう．

In [44]:
# 4x3の配列を作成
numpy_l = np.arange(12).reshape(4, 3)
print(numpy_l.shape)
print(numpy_l)

(4, 3)
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [45]:
# 行ごとの合計
print('行ごとの合計 : ', np.sum(numpy_l, axis = 1))
# 行ごとの平均
print('行ごとの平均 : ', np.mean(numpy_l, axis = 1))

行ごとの合計 :  [ 3 12 21 30]
行ごとの平均 :  [ 1.  4.  7. 10.]


- 行ごとの合計が[ 3 12 21 30]，行ごとの平均が[ 1.  4.  7. 10.]となっていれば正解です．
- 今回の演習を通して確認した関数と軸の関係は以下になります．  

|NumPy関数|軸(axis)|実行結果|
|-|-|-|
|numpy.sum()|無し|全体の総和|
|numpy.sum()|axis=0|列ごとの総和|
|numpy.sum()|axis=1|行ごとの総和|
|numpy.mean()|無し|全体の平均|
|numpy.mean()|axis=0|列ごとの平均|
|numpy.mean()|axis=1|行ごとの平均|