In [2]:
# numpyのインポート
import numpy as np

## 1. 多次元のNumPy配列  
Numpyの配列ndarrayは多次元配列を扱うことができます．  
【例題】二次元以上の配列を生成します．以下のコードを読んで実行してみましょう．

In [3]:
# 2x2x3配列の生成
numpy_l = np.array([[[0, 1, 2], [3, 4, 5]], [[6, 7, 8], [9, 10, 11]]])
print(numpy_l)
print(numpy_l.shape)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
(2, 2, 3)


- 実行結果が  
[[[0 1 2]  
[3 4 5 ]]  
[[6 7 8]  
[9 10 11]]]  
となっていれば成功です．  
- 三次元配列(2x2x3)が生成されていることを確認しましょう．  

【問題1】2x3x3の配列を作ってみましょう．  

In [26]:
print(np.arange(18).reshape(2, 3, 3))

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]


- 2x3x3の配列ができていれば成功です．

## 2. 行列の積  
行列の積を求めるにはnumpy.dot()かnumpy.matmul()を用いることができます．一次元と二次元配列について，使い方を確認しましょう．  

### 一次元配列の積  
一次元配列の積を求めるには，numpy.dot()あるいはnumpy.matmul()の引数にそれぞれ一次元配列を与えることで求めることができます．このとき，二つの配列の要素数が同じである必要がある点に注意しましょう．  
【例題】一次元配列の積をnumpy.dot()とmatmul()を用いて求めてみます．以下のコードを読んで実行してみましょう．

In [9]:
# 配列の生成
numpy_1 = np.arange(5)
print('配列1')
print(numpy_1)
numpy_2 = np.arange(5, 0, -1)
print('配列2')
print(numpy_2)

# 行列の積
print('計算結果')
print(np.dot(numpy_1, numpy_2))
print(np.matmul(numpy_1, numpy_2))

配列1
[0 1 2 3 4]
配列2
[5 4 3 2 1]
計算結果
20
20


- 計算結果がそれぞれ20になっていれば成功です．  
- numpy.dot()とnumpy.matmul()で実行結果が等しいことを確認しましょう．  
- 以降，numpy.dot()で話を進めますが，二次元配列までであれば二つの関数は等価です．

【問題2.1】以下の一次元配列aとbの積を求めてみましょう．
$$
    \boldsymbol{a} =
        \left[\begin{array}{c}
            2 \\
            3 \\
        \end{array}\right] \quad　\\
   \boldsymbol{b} =
        \left[\begin{array}{c}
            4 \\
            5 \\
        \end{array}\right] \quad
$$

In [25]:
# 配列の生成
a = np.array([2, 3])
print('配列1')
print(a)
b = np.array([4, 5])
print('配列2')
print(b)

# 行列の積
print('計算結果')
print(np.dot(a, b))

配列1
[2 3]
配列2
[4 5]
計算結果
23


- 計算結果が23になっていれば正解です．

### 二次元以上の配列の積
二次元以上の配列の積を求める際にもnumpy.dot()とmatmul()を使うことができますが，配列の形状について注意する必要があります．二次元以上の配列の積を求める場合は，一つ目の配列の列数(横方向の要素数)と二つ目の配列の行数(縦方向の要素数)が一致している必要があります．  
【例題】2x3の配列と3x2の配列の積を求めます．以下のコードを読んで実行してみましょう．

In [5]:
# 配列の生成
numpy_1 = np.arange(6).reshape(2, 3)
print('配列1')
print(numpy_1)
numpy_2 = np.arange(6).reshape(3, 2)
print('配列2')
print(numpy_2)

# 行列の積
print('計算結果')
print(np.dot(numpy_1, numpy_2))

配列1
[[0 1 2]
 [3 4 5]]
配列2
[[0 1]
 [2 3]
 [4 5]]
計算結果
[[10 13]
 [28 40]]


- 計算結果が  
[[10 13]  
[28 40]]  
となっていれば成功です．  
- 配列1は2x3,配列2は3x2の配列であり，一つ目の配列の列数と二つ目の配列の行数が一致していることを確認しましょう．  
- 二次元以上の配列もnumpy.dot()によって積が計算できることを確認しましょう．  

【問題2.2】以下の二次元配列aとbの積を求めてみましょう．
$$
    \boldsymbol{a} =
        \left[\begin{array}{c}
            2 & 3 \\
            4 & 5 \\
        \end{array}\right] \quad　\\
   \boldsymbol{b} =
        \left[\begin{array}{c}
            5 & 6 & 7\\
            8 & 9 & 10 \\
        \end{array}\right] \quad
$$

In [24]:
# 配列の生成
a = np.arange(2, 6).reshape(2, 2)
print('配列1')
print(a)
b = np.arange(5, 11).reshape(2, 3)
print('配列2')
print(b)

# 行列の積
print('計算結果')
print(np.dot(a, b))

配列1
[[2 3]
 [4 5]]
配列2
[[ 5  6  7]
 [ 8  9 10]]
計算結果
[[34 39 44]
 [60 69 78]]


- 計算結果が  
[[34 39 44]  
  60 69 78]]  
となっていれば成功です．