In [30]:
# numpyのインポート
import numpy as np

## 1. NumPy配列の要素ごとの最大値・最小値を取得  
numpy.maximum()を用いることで，複数のndarrayの要素ごとの最大値を求め，新たなndarrayを生成することができます．また，numpy.mimimum()を用いることで，同様に最小値を求めることができます.  
【例題1】2つのndarrayの最大値と最小値を求めます．以下のコードを読んで，実行してみましょう．

In [31]:
# 2x3の配列を2つ作成
numpy_1 = np.arange(6).reshape(2, 3)
print('配列その1')
print(numpy_1)

numpy_2 = np.array([[2, 5, 1],[1, 0, 3]])
print('配列その2')
print(numpy_2)

配列その1
[[0 1 2]
 [3 4 5]]
配列その2
[[2 5 1]
 [1 0 3]]


In [32]:
# 要素ごとの最大値を求める
print('要素ごとの最大値')
print(np.maximum(numpy_1, numpy_2))

# 要素ごとの最小値を求める
print('要素ごとの最小値')
print(np.minimum(numpy_1, numpy_2))

要素ごとの最大値
[[2 5 2]
 [3 4 5]]
要素ごとの最小値
[[0 1 1]
 [1 0 3]]


- 要素ごとの最大値が  
[[2 5 2]  
  [3 4 5]]  
最小値が  
[[0 1 1]  
[1 0 3]]  
 となっていれば成功です．  
- 2つの配列の最大値と最小値が要素ごとに求められていることを確認しましょう．

【問題1】以下に示す2つのndarrayの最大値と最小値をそれぞれ求めてみましょう．

In [33]:
# 2x3のndarrayを2つ作成
numpy_1 = np.array([[5, 6, 2], [2, 3, 9]])
print('配列その1')
print(numpy_1)

numpy_2 = np.array([[0, 5, 7],[1, 5, 3]])
print('配列その2')
print(numpy_2)

配列その1
[[5 6 2]
 [2 3 9]]
配列その2
[[0 5 7]
 [1 5 3]]


In [34]:
# 要素ごとの最大値を求める
maximum_ndarray = np.maximum(numpy_1, numpy_2)
print('要素ごとの最大値')
print(maximum_ndarray)

# 要素ごとの最小値を求める
minimum_ndarray = np.minimum(numpy_1, numpy_2)
print('要素ごとの最小値')
print(minimum_ndarray)

要素ごとの最大値
[[5 6 7]
 [2 5 9]]
要素ごとの最小値
[[0 5 2]
 [1 3 3]]


- 要素ごとの最大値が  
[[2 5 2]  
[3 4 5]]  
要素ごとの最小値が  
[[0 1 1]  
[1 0 3]]  
となっていれば正解です.

また，メソッドmax(), min()を用いることで一つの配列の列ごと・行ごとの最大値・最小値を取得することができます．  
【例題2】配列の最大値，最小値を指定した軸ごとに取得します．以下のコードを読んで実行してみましょう．

In [35]:
# 配列の生成
numpy_l = np.array(np.arange(6).reshape(2, 3))
print(numpy_l)

print('列ごとの最大値')
print(numpy_l.max(axis=0))

print('列ごとの最小値')
print(numpy_l.min(axis=0))

[[0 1 2]
 [3 4 5]]
列ごとの最大値
[3 4 5]
列ごとの最小値
[0 1 2]


- 列ごとの最大値が[3 4 5],列ごとの最小値が[0 1 2]となれば成功です．  
- 列ごとにそれぞれ演算が行われていることを確認しましょう．

【問題2】以下の配列の行ごとの最大値，最小値を取得してみましょう．

In [36]:
# 配列
print(numpy_l)

print('列ごとの最大値')
print(numpy_l.max(axis=1))

print('列ごとの最小値')
print(numpy_l.min(axis=1))

[[0 1 2]
 [3 4 5]]
列ごとの最大値
[2 5]
列ごとの最小値
[0 3]


- 列ごとの最大値が[2 5]，最小値が[0 3]となっていれば正解です．

## 2. NumPy配列の比較  
2つのndaarayの要素が等しいかどうかの比較にはnumpy.equal()を使うことができます．また，numpy.all()と合わせて使うことで軸ごとの比較が可能です．  
【例題1】2つのndarrayの要素がそれぞれ等しいかどうかを比較します．以下のコードを読んで実行してみましょう．

In [45]:
# ndarrayの生成
numpy_1 = np.arange(6).reshape(2, 3)
print('配列その1')
print(numpy_1)

numpy_2 = np.array([[0, 1, 2], [0, 1, 2]])
print('配列その2')
print(numpy_2)

配列その1
[[0 1 2]
 [3 4 5]]
配列その2
[[0 1 2]
 [0 1 2]]


In [46]:
# 全ての要素が等しいか比較
print(np.equal(numpy_1, numpy_2))

[[ True  True  True]
 [False False False]]


- 実行結果が，  
[[ True True True]  
[False False False]]  
となれば成功です．
- 値が要素ごとに比較され，結果がブール値で帰ってくることを確認しましょう．

【例題2】np.all()を用いて2つの配列の要素が指定した軸ごとに等しいかどうかを比較します．以下のコードを読んで実行してみましょう．

In [39]:
# 配列の生成
print('配列その1')
print(numpy_1)

print('配列その2')
numpy_2 = np.array([[0, 1, 2], [3, 2, 5]])
print(numpy_2)

配列その1
[[0 1 2]
 [3 4 5]]
配列その2
[[0 1 2]
 [3 2 5]]


In [43]:
print(np.all(np.equal(numpy_1, numpy_2), axis = 0))

[ True False  True]


- 比較結果が[True False True]となっていれば成功です．
- np.allの第一引数に比較演算式を，第二引数に軸を指定することで比較が行われていることを確認しましょう．

【問題】以下の2つの配列の行の要素がそれぞれ等しいか比較してみましょう．

In [41]:
# 配列の生成
print('配列その1')
print(numpy_1)

print('配列その2')
print(numpy_2)

配列その1
[[0 1 2]
 [3 4 5]]
配列その2
[[0 1 2]
 [3 2 5]]


In [44]:
print(np.all(np.equal(numpy_1, numpy_2), axis = 1))

[ True False]


結果が[True False]となっていれば正解です．