In [1]:
# numpyのインポート
import numpy as np

## 1. 配列の要素の並べ替え  
配列の要素をランダムに並べ替えたい場合，numpy.random.permutation()を使うことができます．引数にはintかリスト，配列を与えることができます．この関数は配列をランダムに並べ替え，並べ替えた配列のコピーを生成します．引数にint型のxを渡した場合，np.arange(x)のインデックスをランダムにしたものを生成し，リストまたは配列を渡した場合は要素をランダムに並べ替えます．  
【例題】それでは配列の要素を並べ替えてみます．以下のコードを読んで実行してみましょう．

In [4]:
# 配列の生成
numpy_1 = np.arange(9).reshape(3, 3)
print('配列')
print(numpy_1)

# 配列を並べ替え
numpy_2 = np.random.permutation(numpy_1)

print('numpy_1')
print(numpy_1)
print('numpy_2')
print(numpy_2)

配列
[[0 1 2]
 [3 4 5]
 [6 7 8]]
numpy_1
[[0 1 2]
 [3 4 5]
 [6 7 8]]
numpy_2
[[6 7 8]
 [3 4 5]
 [0 1 2]]


- numpy_1が並べ替える前の配列で，numpy_2が並べ替えた後の配列です．  
- numpy_2の要素が並べ替えられていれば成功です．numpy_1が並べ替えられてnumpy_2が生成されても，numpy_1は上書きされずそのままであることを確認しましょう．また，要素のシャッフルの軸は列ごとです．

【問題】以下の配列をnumpy.random.permutation()を用いて要素を並べ替えてみましょう．

In [8]:
# 配列の生成
numpy_1 = np.arange(9, 0, -1).reshape(3, 3)
print(numpy_1)
print('--------------------')

# 配列の並べ替え
numpy_2 = np.random.permutation(numpy_1)
print(numpy_2)

[[9 8 7]
 [6 5 4]
 [3 2 1]]
--------------------
[[6 5 4]
 [3 2 1]
 [9 8 7]]


- 配列の要素がランダムに並べ替えられていれば成功です．

## 2. 配列から要素をランダムに抽出する  
一次元の配列から要素をランダムに抽出したい場合は，numpy.random.choice()を使うことができます．必要に応じて出現率を指定することも可能です．  
numpy.random.choice(a, size, replace, p)となっており，引数の役割はそれぞれ a:一次元の配列またはint, size:配列から抽出する要素の個数, replace:ブール値で指定し，Trueなら要素の重複あり, p:与えられた配列に対する出現率をリストで指定 となっています．  
【例題】配列から要素をランダムに抽出します．以下のコードを読んで実行してみましょう．

In [16]:
# 配列の生成
numpy_1 = np.arange(3)
print('並べ替える前', numpy_1)

# 要素の抽出
numpy_2 = np.random.choice(numpy_1, 3, replace = True, p=[0.2, 0.2, 0.6])
print('並べ替えた後', numpy_2)

並べ替える前 [0 1 2]
並べ替えた後 [1 2 1]


- 配列が並べ替えられていれば成功です．
- 引数で指定した数だけ要素が抽出されていることを確認しましょう．

【問題】以下の配列の要素を，重複なしで5つ抽出してみましょう．出現率はそれぞれの要素に対して一定とします．

In [17]:
# 配列の生成
numpy_1 = np.arange(10)

# 要素の抽出
numpy_2 = np.random.choice(numpy_1, 5, False)
print(numpy_2)

[2 8 3 4 9]


- 配列の要素を重複なしで5個抽出できれば正解です．