In [0]:
# numpyのインポート
import numpy as np

## 1. 配列の要素のシャッフル   
配列の要素をシャッフルする場合，numpy.random.permutation()を使うことができます．引数にはintかリスト，配列を与えることができます．この関数は配列をシャッフルし，シャッフルした配列のコピーを生成します．引数にint型のxを渡した場合，np.arange(x)の要素をシャッフルしたものを生成し，リストまたは配列を渡した場合は要素をシャッフルします．  
【例題】それでは配列の要素をシャッフルしてみます．以下のコードを読んで実行してみましょう．

In [0]:
# 配列の生成
numpy_1 = np.arange(9).reshape(3, 3)
print('配列')
print(numpy_1)

# 配列の要素をシャッフル
numpy_2 = np.random.permutation(numpy_1)

print('numpy_1')
print(numpy_1)
print('numpy_2')
print(numpy_2)

配列
[[0 1 2]
 [3 4 5]
 [6 7 8]]
numpy_1
[[0 1 2]
 [3 4 5]
 [6 7 8]]
numpy_2
[[3 4 5]
 [0 1 2]
 [6 7 8]]


- numpy_1がシャッフルする前の配列で，numpy_2がシャッフルした後の配列です．  
- numpy_2の要素がシャッフルされていれば成功です．numpy_1がシャッフルされてnumpy_2が生成されても，numpy_1は上書きされずそのままであることを確認しましょう．また，要素のシャッフルの軸は行方向です．

【問題】以下の配列をnumpy.random.permutation()を用いて要素をシャッフルしてみましょう．

In [0]:
# 配列の生成
numpy_1 = np.arange(9, 0, -1).reshape(3, 3)
print(numpy_1)
print('--------------------')

# 配列の要素のシャッフル
numpy_2 = np.random.permutation(numpy_1)
print(numpy_2)

[[9 8 7]
 [6 5 4]
 [3 2 1]]
--------------------
[[6 5 4]
 [3 2 1]
 [9 8 7]]


- 配列の要素がランダムに並べ替えられていれば成功です．

#### ミニバッチ処理で用いる手法  
次にミニバッチ処理の基本となる，シャッフルされたデータを指定された個数ずつ選ぶ方法を解説します．  
10個ずつ選ぶやり方を考えます．まずnumpy.random.permutation()を用いてデータをシャッフルし，次にnp.arange()でシャッフルされたデータの配列に対して10個ずつの等差数列を生成します．等差数列を用いてfor文を回し，for文の中でデータを取り出します．  
以下のコードを読んで実行してみましょう．

In [0]:
# データとバッチサイズの定義
data = np.arange(50)
print('データ')
print(data)
batch_size = 10
cnt = 0

# データのインデックスをシャッフル
perm = np.random.permutation(len(data))

# 10個ずつデータを取り出す
for idx in np.arange(0, len(perm), batch_size): # 等差10の等差数列を用いる
    cnt = cnt + 1
    x = data[perm[idx:idx + batch_size]] # データの取り出し
    print("ミニバッチ" + str(cnt))
    print(x)

データ
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
ミニバッチ1
[21 23 38  1 26  5 13 18 30  6]
ミニバッチ2
[ 7 12 45 32  8 46  2 40 36 24]
ミニバッチ3
[20 29  0 14 19  4 49 31  9 48]
ミニバッチ4
[16  3 37 11 42 47 22 43 25 34]
ミニバッチ5
[10 15 41 33 28 27 44 35 39 17]


## 2. 配列から要素をランダムに抽出する  
一次元の配列から要素をランダムに抽出したい場合は，numpy.random.choice()を使うことができます．必要に応じて出現率を指定することも可能です．  
numpy.random.choice(a, size, replace, p)となっており，引数の役割はそれぞれ a:一次元の配列またはint, size:配列から抽出する要素の個数, replace:ブール値で指定し，Trueなら要素の重複あり, p:与えられた配列に対する出現率をリストで指定 となっています．  
【例題】配列から要素をランダムに抽出します．以下のコードを読んで実行してみましょう．

In [0]:
# 配列の生成
numpy_1 = np.arange(3)
print('並べ替える前', numpy_1)

# 要素の抽出
numpy_2 = np.random.choice(numpy_1, 3, replace = True, p=[0.2, 0.2, 0.6])
print('並べ替えた後', numpy_2)

並べ替える前 [0 1 2]
並べ替えた後 [1 2 1]


- 配列が並べ替えられていれば成功です．
- 引数で指定した数だけ要素が抽出されていることを確認しましょう．

【問題】以下の配列の要素を，重複なしで5つ抽出してみましょう．出現率はそれぞれの要素に対して一定とします．

In [0]:
# 配列の生成
numpy_1 = np.arange(10)

# 要素の抽出
numpy_2 = np.random.choice(numpy_1, 5, False)
print(numpy_2)

[2 8 3 4 9]


- 配列の要素を重複なしで5個抽出できれば正解です．