In [1]:
# numpyのインポート
import numpy as np

## 1. ブールインデックス参照  
配列の各要素に対してブール値を与えることで，Trueの部分の要素を取り出した配列を新たに生成することができます．  
【例題】ブールインデックス参照を用いて要素の取り出しを行います．以下のコードを読んで実行してみましょう．

In [6]:
# 配列の生成
numpy_l = np.arange(5)
print(numpy_l)

# ブールインデックス参照を用いて取り出し
print('実行結果')
print(numpy_l[np.array([True, True, True, False, False]) ])

[0 1 2 3 4]
実行結果
[0 1 2]


- 実行結果が  
[0 1 2]  
となっていれば成功です．  
- このように，ブール値を与えることで要素を取り出すことができることを確認しましょう．
- また，ブール値ではなく条件式を書くことで各要素について比較することができます．

In [9]:
print(numpy_l)

# 比較する
print('実行結果')
print(numpy_l[numpy_l < 3])

[0 1 2 3 4]
実行結果
[0 1 2]


- このように条件式に合う値を取り出すことができます．

【問題】以下の配列について，10で割り切れるものに-1を代入してみましょう．

In [14]:
# 配列の生成
numpy_l = np.array([0, 5, 10, 15, 20, 25, 30])

# 比較
numpy_l[numpy_l % 10 == 0] = -1

print(numpy_l)

[-1  5 -1 15 -1 25 -1]


- 生成された配列が  
[-1 5 -1 15 -1 25 -1]  
となっていれば正解です．